openapi: "3.0.3"
info:
  title: Tax-Free Childcare payment integration API
  description: "An API which allows online cashless payment providers to give parents the option of paying for their childcare with funds from their Tax-Free Childcare (TFC) account.
  
  
  There are 3 different operations involved in this process:

- Linking the parent's TFC account with their account on the online payment provider's platform.

- Checking the balance on the child's TFC account.

- Making one-off payments from the child's TFC account to the childcare provider.

## Error mapping

The following table gives the detailed description for each error code you receive from the API:

<table>
	<thead>
		<tr>
			<th>Error code</th>
			<th>Error description</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>ETFC1</td>
			<td>Correlation-ID is in an invalid format or missing</td>
		</tr>
		<tr>
			<td>ETFC2</td>
			<td>Bearer Token did not return a valid record</td>
		</tr>
		<tr>
			<td>ETFC3</td>
			<td>Bad Gateway</td>
		</tr>
		<tr>
			<td>ETFC4</td>
			<td>Bad Gateway</td>
		</tr>
		<tr>
			<td>E0000</td>
			<td>We encountered an error on our servers and did not process your request, please try again later.</td>
		</tr>
		<tr>
			<td>E0001</td>
			<td>outbound_child_payment_ref is in invalid format or missing</td>
		</tr>
		<tr>
			<td>E0002</td>
			<td>epp_reg_reference is in invalid format or missing</td>
		</tr>
		<tr>
			<td>E0003</td>
			<td>ccp_reg_reference is in invalid format or missing</td>

		</tr>
		<tr>
			<td>E0004</td>
			<td>epp_unique_customer_id is in invalid format or missing</td>

		</tr>
		<tr>
			<td>E0024</td>
			<td>Please check that the epp_reg_reference and epp_unique_customer_id are both correct</td>
		</tr>
		<tr>
			<td>E0025</td>
			<td>Please check that the child_date_of_birth and outbound_child_payment_ref are both correct</td>
		</tr>
		<tr>
			<td>E0026</td>
			<td>Please check the outbound_child_payment_ref supplied</td>
		</tr>
		<tr>
			<td>E0027</td>
			<td>The Childcare Provider (CCP) you have specified is not linked to the TFC Account. Please ensure that the parent goes into their TFC Portal and adds the CCP to their account first before attempting payment again later.</td>
		</tr>
		<tr>
			<td>E0030</td>
			<td>The External Payment Provider (EPP) record is inactive on the TFC system. Please ensure EPP completes sign up process on TFC Portal or contact HMRC POC for further information.</td>
		</tr>
		<tr>
			<td>E0031</td>
			<td>The Childcare Provider's(CCP) account is inactive, please check the CCP details and ensure that the CCP is still registered with their childcare regulator and that they have also signed up to TFC via the TFC portal to receive TFC funds.</td>
		</tr>
		<tr>
			<td>E0032</td>
			<td>The epp_unique_customer_id or epp_reg_reference is not associated with the outbound_child_payment_ref</td>
		</tr>
		<tr>
			<td>E0033</td>
			<td>The TFC account used to request payment contains insufficient funds</td>
		</tr>
		<tr>
			<td>E0035</td>
			<td>There is an issue with this TFC Account, please advise parent / carer to contact TFC customer Services</td>
		</tr>
		<tr>
			<td>E0036</td>
			<td>Error processing payment due to Payee bank details</td>
		</tr>
		<tr>
			<td>E0040</td>
			<td>The outbound_child_payment_ref could not be found in the TFC system - please ensure parent checks their details and tries again.</td>
		</tr>
		<tr>
			<td>E0041</td>
			<td>The epp_reg_reference could not be found in the TFC system. Please check the details and try again.	</td>
		</tr>
		<tr>
			<td>E0042</td>
			<td>The ccp_reg_reference could not be found in the TFC system or does not correlate with the ccp_postcode. Please check the details and try again.	</td>
		</tr>
		<tr>
			<td>E0043</td>
			<td>Parent associated with the bearer token does not have a TFC account. Please ask the parent to create a TFC account first.</td>
		</tr>
	</tbody>
</table>
"
  version: 1.2.0
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
tags:
- name: Link accounts
- name: Check balance
- name: Make payment
paths: 
  /individuals/tax-free-childcare/payments/link:
   post:
      tags:
      - Link accounts
      summary: Linking the parent's online payment provider account to their TFC account
      description: 
        "This endpoint links the parent's TFC account with an account they hold with an online payment provider. This linking will be initiated by the payment provider's platform when offering TFC to the parent as an option to pay for their child's care. The parent will be required to confirm if they want this link to be created. This link is essential if the parent wishes to use TFC within the payment provider's platform."
      parameters:
      - name: Accept
        in: header
        description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)
          of the API to be used.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/vnd.hmrc.1.2+json
      - name: Correlation-ID
        in: header
        required: true
        style: simple
        explode: false
        description: A unique key shared between all parties which can be used for tracing and error tracking. This 32 character, hyphen separated alphanumeric string is generated and sent by the online payment provider.
        schema:
          format: uuid
          type: string
          example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                epp_unique_customer_id:
                  description: This 11 character, numeric, unique ID is assigned to the online payment provider by NS&I. For guidance from NS&I on how to register with them, refer to [How do I sign up as a provider?](https://www.childcarechoices.gov.uk/guidance-and-resources/information-childcare-providers/tax-free-childcare).
                  type: string
                  example: "12345678901"
                epp_reg_reference:
                  description: This alphanumeric unique ID (max. 20 characters) is assigned to the online payment provider when they register with HMRC.
                  type: string
                  example: 1a2b3c4d5e6f7g8h
                outbound_child_payment_ref:
                  description: The 12 character alphanumeric reference number the parent uses when making payments to the CCP. This number is displayed on the TFC portal, and is used by the CCP to allocate incoming funds to the correct child's account. The format is 4 letters, representing the first initial of the child's first name and the first 3 initials of the child's last name, 5 numbers, and ending in 'TFC'.
                  type: string
                  example: ABCD12345TFC
                child_date_of_birth:
                  description: The date of birth (YYYY-MM-DD) of the child whose accounts are being linked. This extra identity check is used to cross-reference with the child's details held by the online payment provider.  
                  type: string
                  example: 2020-01-01

      responses:
          "200":
            description: Confirmation that a link has been established
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    child_full_name:
                      type: string
                      description: The full name of the child whose accounts have been linked. Providing this confirms the link has been successful.
                      example: Jane Doe
          "400":
            description: Bad request
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/400errorResponseLink'
                  examples:
                    bad_request:
                      value:
                        errorCode: "E0030"
                        errorDescription: "The External Payment Provider (EPP) record is inactive on the TFC system. Please ensure EPP completes sign up process on TFC Portal or contact HMRC POC for further information."
          "500":
            description: Internal server error
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/500errorResponseLink'
                  examples:
                    internal_server_error:
                      value:
                        errorCode: E0401
                        errorDescription: "We encountered an error on our servers and did not process your request, please try again later."
      security:
        - user-restricted:
          - tax-free-childcare-payments
      
  /individuals/tax-free-childcare/payments/balance:
    post:
      tags:
      - Check balance
      summary: Retrieving the balance of the associated child's TFC account
      description: 
        "This endpoint fetches the balance of the associated child's TFC account. The balance of the TFC account consists of the following three different elements:
        
        - Paid in by you - the amount of money the parent or guardian has paid into the child's account.
        
        - Government top-up - the amount of top-up funds paid in by the government.
        
        - Total balance - the sum of the two previous amounts."
      parameters:
       - name: Accept
         in: header
         description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)
          of the API to be used.
         required: true
         style: simple
         explode: false
         schema:
           type: string
           enum:
           - application/vnd.hmrc.1.2+json
       - name: Correlation-ID
         in: header
         required: true
         style: simple
         explode: false
         description: A unique key shared between all parties which can be used for tracing and error tracking. This 32 character, hyphen separated alphanumeric string is generated and sent by the online payment provider.
         schema:
           format: uuid
           type: string
           example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                epp_unique_customer_id:
                  description: This 11 character, numeric, unique ID is assigned to the online payment provider by NS&I. For guidance from NS&I on how to register with them, refer to [How do I sign up as a provider?](https://www.childcarechoices.gov.uk/guidance-and-resources/information-childcare-providers/tax-free-childcare).
                  type: string
                  example: "12345678901"
                epp_reg_reference:
                  description: This alphanumeric unique ID (max. 20 characters) is assigned to the online payment provider when they register with HMRC.
                  type: string
                  example: 1a2b3c4d5e6f7g8h
                outbound_child_payment_ref:
                  description:  The 12 character alphanumeric reference number the parent uses when making payments to the CCP. This number is displayed on the TFC portal, and is used by the CCP to allocate incoming funds to the correct child's account. The format is 4 letters, representing the first initial of the child's first name and the first 3 initials of the child's last name, 5 numbers, and ending in 'TFC'. 
                  type: string
                  example: ABCD12345TFC
      responses:
          "200":
            description: The TFC account balance is returned
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    tfc_account_status:
                      type: string
                      description: The status of the child's TFC account. Indicates whether the account is active or not.
                      enum:
                       - Active
                       - Inactive
                      example: Active
                    paid_in_by_you:
                      type: integer
                      description: The amount of money paid in to the child's TFC account by the parent or guardian. Supplied as 1/100 of the currency, therefore sterling pence. For example, 20000 = £200.00.
                      example: 80000
                    government_top_up:
                      type: integer
                      description: The amount paid in by the government, this amount has cleared and is available to the parent or guardian. Supplied as 1/100 of the currency, therefore sterling pence. For example, 20000 = £200.00.
                      example: 20000
                    total_balance:
                      type: integer
                      description: The sum of paid_in_by_you and government_top_up, this is the total amount paid into the account. Supplied as 1/100 of the currency, therefore sterling pence. For example, 20000 = £200.00.
                      example: 100000
                    cleared_funds:
                      type: integer
                      description: The total amount of money available to the parent or guardian to use to make payments to childcare providers. This is equal to total_balance minus any uncleared funds from paid_in_by_you. Supplied as 1/100 of the currency, therefore sterling pence. For example, 20000 = £200.00. Requested payments can not exceed this amount.
                      example: 100000
                    top_up_allowance:
                      type: integer
                      description: The remaining amount of government top-up that is available to the parent or guardian for the current quarter. The amount that is paid in to the account by the government depends on what the parent or guardian pays in. Supplied as 1/100 of the currency, therefore sterling pence. For example, 20000 = £200.00.
                      example: 15000
          "400":
            description: Bad request
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/400errorResponseBalance'
                  examples:
                    bad_request:
                      value:
                        errorCode: "E0030"
                        errorDescription: "The External Payment Provider (EPP) record is inactive on the TFC system. Please ensure EPP completes sign up process on TFC Portal or contact HMRC POC for further information"
          "500":
            description: Internal server error
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/500errorResponseBalance'
                  examples:
                    internal_server_error:
                      value:
                        errorCode: E0401
                        errorDescription: "We encountered an error on our servers and did not process your request, please try again later."
      security:
        - user-restricted:
          - tax-free-childcare-payments
      

  /individuals/tax-free-childcare/payments/:
    post:
      tags:
      - Make payment
      summary: Sending payment from the TFC account to the intended recipient
      description: 
        "This endpoint requests the payment of the selected amount from the child's TFC account to the intended recipient."
      parameters:
      - name: Accept
        in: header
        description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)
          of the API to be used.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/vnd.hmrc.1.2+json
      - name: Correlation-ID
        in: header
        required: true
        style: simple
        explode: false
        description: A unique key shared between all parties which can be used for tracing and error tracking. This 32 character, hyphen separated alphanumeric string is generated and sent by the online payment provider.
        schema:
          format: uuid
          type: string
          example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                outbound_child_payment_ref:
                  description:  The 12 character alphanumeric reference number the parent uses when making payments to the CCP. This number is displayed on the TFC portal, and is used by the CCP to allocate incoming funds to the correct child's account. The format is 4 letters, representing the first initial of the child's first name and the first 3 initials of the child's last name, 5 numbers, and ending in 'TFC'. 
                  type: string
                  example: ABCD12345TFC
                epp_unique_customer_id:
                  description: This 11 character, numeric, unique ID is assigned to the online payment provider by NS&I. For guidance from NS&I on how to register with them, refer to [How do I sign up as a provider?](https://www.childcarechoices.gov.uk/guidance-and-resources/information-childcare-providers/tax-free-childcare).
                  type: string
                  example: "12345678901"
                epp_reg_reference:
                  description: This alphanumeric unique ID (max. 20 characters) is assigned to the online payment provider when they register with HMRC.
                  type: string
                  example: 1a2b3c4d5e6f7g8h
                payment_amount:
                  description: The amount of money the parent or guardian wants to pay the childcare provider from their TFC balance. Supplied as 1/100 of the currency, therefore sterling pence. For example, 20000 = £200.00. Requested payments can not exceed this amount.
                  type: integer
                  example: 20000
                ccp_reg_reference:
                  description: The unique reference number given to the childcare provider by the childcare regulator (such as Ofsted). The online payment provider needs to provide this to HMRC. 
                  type: string
                  example: EY456798
                ccp_postcode:
                  description: The postcode associated with the childcare provider, this enables further verification.
                  type: string
                  example: AB12 3CD
                payee_type:
                  description: The initial recipient of the funds from the child's TFC account. Only `CCP` is available, meaning funds are paid directly to the childcare provider.
                  type: string
                  enum:
                  - CCP
      responses:
          "200":
            description: Confirmation the payment was succesful
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    payment_reference:
                      type: string
                      description: A unique identifier that is used as confirmation that the payment has been successful. This can be used to track the payment.
                      example: C4E09ZY4A00A0009
                    estimated_payment_date:
                      type: string
                      description: The estimated date (YYYY-MM-DD) the payment will leave the child's TFC account. This is used for audit purposes and to give childcare providers an expectation of when they will receive funds.
                      example: 2024-10-10
          "400":
            description: Bad request
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/400errorResponsePayment'
                  examples:
                    bad_request:
                      value:
                        errorCode: "E0030"
                        errorDescription: "The External Payment Provider (EPP) record is inactive on the TFC system. Please ensure EPP completes sign up process on TFC Portal or contact HMRC POC for further information."
          "500":
            description: Internal server error
            headers:
              Correlation-ID:
                schema:
                  format: uuid
                  type: string
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  example: 5fb3b626-7399-48c2-a92a-b97ed8d6fed7
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/500errorResponsePayment'
                  examples:
                    internal_server_error:
                      value:
                        errorCode: E0401
                        errorDescription: "We encountered an error on our servers and did not process your request, please try again later."
      security:
        - user-restricted:
          - tax-free-childcare-payments
      
components:
  securitySchemes:
    user-restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints)
        API requests using an OAuth 2.0 Bearer Token in the Authorization header.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            tax-free-childcare-payments: Access all aspects of Tax Free Childcare Payments API
  schemas:
    400errorResponseLink:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC1, E0001, E0002, E0004, E0006, E0024, E0025, E0026, E0030, E0040, E0041, E0043"
          type: string
        errorMessage:
          description: Refer to the [Error mapping table](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/tax-free-childcare-payments/1.2/oas/page#section/Error-mapping) for the corresponding error message.
          type: string

    400errorResponseBalance:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC1, E0001, E0002, E0004, E0024, E0026, E0030, E0040, E0041, E0043"
          type: string
        errorMessage:
          description: Refer to the [Error mapping table](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/tax-free-childcare-payments/1.2/oas/page#section/Error-mapping) for the corresponding error message.
          type: string

    400errorResponsePayment:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC1, E0001, E0002, E0003, E0007, E0008, E0009, E0024, E0026, E0027, E0030, E0031, E0033, E0035, E0036, E0040, E0041, E0042, E0043"
          type: string
        errorMessage:
          description: Refer to the [Error mapping table](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/tax-free-childcare-payments/1.2/oas/page#section/Error-mapping) for the corresponding error message.
          type: string

    500errorResponseLink:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC2, E0000, E0002, E0004, E0005, E0006, E0021, E0022, E0023, E0401, E0001"
          type: string
        errorMessage:
          description: We encountered an error on our servers and did not process your request, please try again later.	
          type: string

    500errorResponseBalance:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC2, E0000, E0002, E0004, E0005, E0401, E0001"
          type: string
        errorMessage:
          description: We encountered an error on our servers and did not process your request, please try again later.	
          type: string

    500errorResponsePayment:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC2, E0000, E0002, E0003, E0004, E0005, E0007, E0008, E0009, E0022, E0023, E0401, E0001"
          type: string
        errorMessage:
          description: We encountered an error on our servers and did not process your request, please try again later.	
          type: string


    502errorResponse:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: ETFC3, E0020"
          type: string
        errorMessage:
          description: Bad Gateway.
          type: string

    503errorResponse:
      description: Refer to the Error mapping table above for full details of the error.
      type: object
      properties:
        errorCode:
          description: "One of the following error codes: E0034,E9000, E9999, E8000, E8001"
          type: string
        errorMessage:
          description: The service is currently unavailable.
          type: string